// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WildAnimalsAPI.Persistence;

#nullable disable

namespace WildAnimalsAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240322035410_add-seeder-continents2")]
    partial class addseedercontinents2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarvelPersonalProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WildAnimalsAPI.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AverageHeightMax")
                        .HasColumnType("int");

                    b.Property<int>("AverageHeightMin")
                        .HasColumnType("int");

                    b.Property<int>("AverageLifespanMax")
                        .HasColumnType("int");

                    b.Property<int>("AverageLifespanMin")
                        .HasColumnType("int");

                    b.Property<int>("AverageSpeedMax")
                        .HasColumnType("int");

                    b.Property<int>("AverageSpeedMin")
                        .HasColumnType("int");

                    b.Property<int>("AverageWeightMax")
                        .HasColumnType("int");

                    b.Property<int>("AverageWeightMin")
                        .HasColumnType("int");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstimatedPopulationSize")
                        .HasColumnType("int");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("WildAnimalsAPI.Models.AnimalContinent", b =>
                {
                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<int>("ContinentId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("AnimalId", "ContinentId");

                    b.HasIndex("ContinentId");

                    b.ToTable("AnimalContinents");
                });

            modelBuilder.Entity("WildAnimalsAPI.Models.Continent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.Property<long>("SurfaceKm2")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Continents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Asia",
                            Population = 4693000000L,
                            SurfaceKm2 = 44614000L
                        },
                        new
                        {
                            Id = 2,
                            Name = "Africa",
                            Population = 1386000000L,
                            SurfaceKm2 = 30370000L
                        },
                        new
                        {
                            Id = 3,
                            Name = "America del Norte",
                            Population = 593000000L,
                            SurfaceKm2 = 24709000L
                        },
                        new
                        {
                            Id = 4,
                            Name = "America del Sur",
                            Population = 434000000L,
                            SurfaceKm2 = 17843000L
                        },
                        new
                        {
                            Id = 5,
                            Name = "Antártida",
                            Population = 0L,
                            SurfaceKm2 = 14200000L
                        },
                        new
                        {
                            Id = 6,
                            Name = "Europa",
                            Population = 741000000L,
                            SurfaceKm2 = 10180000L
                        },
                        new
                        {
                            Id = 7,
                            Name = "Oceanía",
                            Population = 44000000L,
                            SurfaceKm2 = 8920000L
                        });
                });

            modelBuilder.Entity("WildAnimalsAPI.Models.AnimalContinent", b =>
                {
                    b.HasOne("WildAnimalsAPI.Models.Animal", "Animal")
                        .WithMany("Continents")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WildAnimalsAPI.Models.Continent", "Continent")
                        .WithMany("Animals")
                        .HasForeignKey("ContinentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Continent");
                });

            modelBuilder.Entity("WildAnimalsAPI.Models.Animal", b =>
                {
                    b.Navigation("Continents");
                });

            modelBuilder.Entity("WildAnimalsAPI.Models.Continent", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
