// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WildAnimalsAPI.Persistence;

#nullable disable

namespace WildAnimalsAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240331232355_add-seeder-animals")]
    partial class addseederanimals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarvelPersonalProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WildAnimalsAPI.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AverageHeightMax")
                        .HasColumnType("int");

                    b.Property<int>("AverageHeightMin")
                        .HasColumnType("int");

                    b.Property<int>("AverageLifespanMax")
                        .HasColumnType("int");

                    b.Property<int>("AverageLifespanMin")
                        .HasColumnType("int");

                    b.Property<int>("AverageSpeedMax")
                        .HasColumnType("int");

                    b.Property<int>("AverageSpeedMin")
                        .HasColumnType("int");

                    b.Property<int>("AverageWeightMax")
                        .HasColumnType("int");

                    b.Property<int>("AverageWeightMin")
                        .HasColumnType("int");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstimatedPopulationSize")
                        .HasColumnType("int");

                    b.Property<string>("Locations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageHeightMax = 38,
                            AverageHeightMin = 28,
                            AverageLifespanMax = 20,
                            AverageLifespanMin = 15,
                            AverageSpeedMax = 100,
                            AverageSpeedMin = 55,
                            AverageWeightMax = 14,
                            AverageWeightMin = 6,
                            CommonName = "Bald Eagle",
                            Description = "The bald eagle is a large bird of prey native to North America. It has a distinctive white head and brown body, and is known for its exceptional eyesight and hunting abilities.",
                            Diet = "Carnivore",
                            EstimatedPopulationSize = 150000,
                            Locations = "3",
                            ScientificName = "haliaeetus leucocephalus"
                        },
                        new
                        {
                            Id = 2,
                            AverageHeightMax = 16,
                            AverageHeightMin = 13,
                            AverageLifespanMax = 15,
                            AverageLifespanMin = 10,
                            AverageSpeedMax = 15,
                            AverageSpeedMin = 10,
                            AverageWeightMax = 30,
                            AverageWeightMin = 18,
                            CommonName = "Beagle",
                            Description = "The Beagle is a breed of small, compact dogs that are known for their gentle and friendly nature, as well as their exceptional sense of smell.",
                            Diet = "Omnivore",
                            EstimatedPopulationSize = 1000000,
                            Locations = "6",
                            ScientificName = "Canis lupus"
                        },
                        new
                        {
                            Id = 3,
                            AverageHeightMax = 24,
                            AverageHeightMin = 18,
                            AverageLifespanMax = 14,
                            AverageLifespanMin = 10,
                            AverageSpeedMax = 20,
                            AverageSpeedMin = 15,
                            AverageWeightMax = 70,
                            AverageWeightMin = 40,
                            CommonName = "Beagle Shepherd",
                            Description = "The Beagle Shepherd is a hybrid breed that combines the intelligence and protective nature of the German Shepherd with the friendly and playful character of the Beagle.",
                            Diet = "Omnivore",
                            EstimatedPopulationSize = 10000,
                            Locations = "3",
                            ScientificName = "Canis lupus"
                        },
                        new
                        {
                            Id = 4,
                            AverageHeightMax = 16,
                            AverageHeightMin = 12,
                            AverageLifespanMax = 14,
                            AverageLifespanMin = 10,
                            AverageSpeedMax = 15,
                            AverageSpeedMin = 10,
                            AverageWeightMax = 25,
                            AverageWeightMin = 15,
                            CommonName = "Cheagle",
                            Description = "The Cheagle is a hybrid breed that combines the playful and affectionate nature of the Beagle with the loyalty and intelligence of the Chihuahua.",
                            Diet = "Omnivore",
                            EstimatedPopulationSize = 5000,
                            Locations = "3",
                            ScientificName = "Canis lupus"
                        },
                        new
                        {
                            Id = 5,
                            AverageHeightMax = 100,
                            AverageHeightMin = 40,
                            AverageLifespanMax = 30,
                            AverageLifespanMin = 15,
                            AverageSpeedMax = 100,
                            AverageSpeedMin = 60,
                            AverageWeightMax = 15,
                            AverageWeightMin = 2,
                            CommonName = "Eagle",
                            Description = "Eagles are large birds of prey that belong to the family Accipitridae. They are known for their powerful wings, sharp talons, and excellent eyesight, which make them skilled hunters.",
                            Diet = "Carnivore",
                            EstimatedPopulationSize = 1000000,
                            Locations = "2;1;6;3;4",
                            ScientificName = "Accipitridae"
                        },
                        new
                        {
                            Id = 6,
                            AverageHeightMax = 102,
                            AverageHeightMin = 89,
                            AverageLifespanMax = 35,
                            AverageLifespanMin = 25,
                            AverageSpeedMax = 50,
                            AverageSpeedMin = 30,
                            AverageWeightMax = 20,
                            AverageWeightMin = 11,
                            CommonName = "Harpy Eagle",
                            Description = "The Harpy Eagle is one of the largest and most powerful birds of prey in the world, found in the tropical forests of Central and South America.",
                            Diet = "Carnivore",
                            EstimatedPopulationSize = 50000,
                            Locations = "3;4",
                            ScientificName = "Harpia harpyja"
                        },
                        new
                        {
                            Id = 7,
                            AverageHeightMax = 16,
                            AverageHeightMin = 12,
                            AverageLifespanMax = 15,
                            AverageLifespanMin = 12,
                            AverageSpeedMax = 15,
                            AverageSpeedMin = 10,
                            AverageWeightMax = 30,
                            AverageWeightMin = 20,
                            CommonName = "Malteagle",
                            Description = "The Malteagle is a hybrid breed that combines the playful and affectionate nature of the Maltese with the intelligence and loyalty of the Beagle.",
                            Diet = "Omnivore",
                            EstimatedPopulationSize = 2000,
                            Locations = "3",
                            ScientificName = "Canis lupus"
                        },
                        new
                        {
                            Id = 8,
                            AverageHeightMax = 16,
                            AverageHeightMin = 12,
                            AverageLifespanMax = 15,
                            AverageLifespanMin = 10,
                            AverageSpeedMax = 15,
                            AverageSpeedMin = 10,
                            AverageWeightMax = 25,
                            AverageWeightMin = 15,
                            CommonName = "Meagle",
                            Description = "The Meagle is a hybrid breed that combines the friendly and playful nature of the Beagle with the intelligence and alertness of the Miniature Schnauzer.",
                            Diet = "Omnivore",
                            EstimatedPopulationSize = 3000,
                            Locations = "3",
                            ScientificName = "Canis lupus"
                        },
                        new
                        {
                            Id = 9,
                            AverageHeightMax = 65,
                            AverageHeightMin = 50,
                            AverageLifespanMax = 26,
                            AverageLifespanMin = 20,
                            AverageSpeedMax = 40,
                            AverageSpeedMin = 30,
                            AverageWeightMax = 4,
                            AverageWeightMin = 3,
                            CommonName = "Mexican Eagle (Northern crested caracara)",
                            Description = "The Northern Crested Caracara, also known as the Mexican Eagle, is a unique bird of prey found in the southern United States, Mexico, and Central America.",
                            Diet = "Carnivore",
                            EstimatedPopulationSize = 100000,
                            Locations = "3;4",
                            ScientificName = "Caracara cheriway"
                        },
                        new
                        {
                            Id = 10,
                            AverageHeightMax = 16,
                            AverageHeightMin = 12,
                            AverageLifespanMax = 14,
                            AverageLifespanMin = 12,
                            AverageSpeedMax = 15,
                            AverageSpeedMin = 10,
                            AverageWeightMax = 20,
                            AverageWeightMin = 15,
                            CommonName = "Peagle",
                            Description = "The Peagle is a hybrid breed that combines the friendly and playful nature of the Beagle with the intelligence and alertness of the Pug.",
                            Diet = "Omnivore",
                            EstimatedPopulationSize = 4000,
                            Locations = "3",
                            ScientificName = "Canis lupus"
                        },
                        new
                        {
                            Id = 11,
                            AverageHeightMax = 14,
                            AverageHeightMin = 10,
                            AverageLifespanMax = 15,
                            AverageLifespanMin = 10,
                            AverageSpeedMax = 15,
                            AverageSpeedMin = 10,
                            AverageWeightMax = 20,
                            AverageWeightMin = 10,
                            CommonName = "Pocket Beagle",
                            Description = "The Pocket Beagle is a miniature version of the classic Beagle breed, known for its friendly and curious nature, as well as its compact size.",
                            Diet = "Omnivore",
                            EstimatedPopulationSize = 20000,
                            Locations = "6",
                            ScientificName = "Canis lupus"
                        },
                        new
                        {
                            Id = 12,
                            AverageHeightMax = 18,
                            AverageHeightMin = 14,
                            AverageLifespanMax = 15,
                            AverageLifespanMin = 12,
                            AverageSpeedMax = 15,
                            AverageSpeedMin = 10,
                            AverageWeightMax = 30,
                            AverageWeightMin = 20,
                            CommonName = "Pomeagle",
                            Description = "The Pomeagle is a hybrid breed that combines the friendly and playful nature of the Beagle with the intelligence and affection of the Pomeranian.",
                            Diet = "Omnivore",
                            EstimatedPopulationSize = 2500,
                            Locations = "3",
                            ScientificName = "Canis lupus"
                        },
                        new
                        {
                            Id = 13,
                            AverageHeightMax = 360,
                            AverageHeightMin = 150,
                            AverageLifespanMax = 30,
                            AverageLifespanMin = 20,
                            AverageSpeedMax = 20,
                            AverageSpeedMin = 10,
                            AverageWeightMax = 500,
                            AverageWeightMin = 100,
                            CommonName = "Porbeagle Shark",
                            Description = "The Porbeagle Shark is a large, robust shark species found in the cold and temperate waters of the North Atlantic and Southern Hemisphere oceans.",
                            Diet = "Carnivore",
                            EstimatedPopulationSize = 200000,
                            Locations = "7",
                            ScientificName = "Lamna nasus"
                        },
                        new
                        {
                            Id = 14,
                            AverageHeightMax = 18,
                            AverageHeightMin = 14,
                            AverageLifespanMax = 15,
                            AverageLifespanMin = 12,
                            AverageSpeedMax = 15,
                            AverageSpeedMin = 10,
                            AverageWeightMax = 30,
                            AverageWeightMin = 20,
                            CommonName = "Schneagle",
                            Description = "The Schneagle is a hybrid breed that combines the friendly and playful nature of the Beagle with the intelligence and alertness of the Miniature Schnauzer.",
                            Diet = "Omnivore",
                            EstimatedPopulationSize = 3500,
                            Locations = "3",
                            ScientificName = "Canis lupus"
                        },
                        new
                        {
                            Id = 15,
                            AverageHeightMax = 100,
                            AverageHeightMin = 60,
                            AverageLifespanMax = 25,
                            AverageLifespanMin = 15,
                            AverageSpeedMax = 98,
                            AverageSpeedMin = 50,
                            AverageWeightMax = 9,
                            AverageWeightMin = 2,
                            CommonName = "Sea Eagle",
                            Description = "Sea eagles are large birds of prey that belong to the genus Haliaeetus and are found near coastal regions around the world.",
                            Diet = "Carnivore",
                            EstimatedPopulationSize = 1000000,
                            Locations = "2;5;1;6;3;7",
                            ScientificName = "Haliaeetus"
                        },
                        new
                        {
                            Id = 16,
                            AverageHeightMax = 94,
                            AverageHeightMin = 66,
                            AverageLifespanMax = 25,
                            AverageLifespanMin = 20,
                            AverageSpeedMax = 46,
                            AverageSpeedMin = 30,
                            AverageWeightMax = 6,
                            AverageWeightMin = 4,
                            CommonName = "White-Tailed Eagle",
                            Description = "The White-Tailed Eagle is a large bird of prey found in Eurasia and North America, known for its distinctive white tail and impressive wingspan.",
                            Diet = "Carnivore",
                            EstimatedPopulationSize = 30000,
                            Locations = "1;6;3",
                            ScientificName = "Haliaeetus albicilla"
                        },
                        new
                        {
                            Id = 17,
                            AverageHeightMax = 84,
                            AverageHeightMin = 60,
                            AverageLifespanMax = 20,
                            AverageLifespanMin = 10,
                            AverageSpeedMax = 30,
                            AverageSpeedMin = 20,
                            AverageWeightMax = 90,
                            AverageWeightMin = 29,
                            CommonName = "Cougar",
                            Description = "El puma o cougar es el felino más grande de América del Norte, conocido por sus poderosas extremidades delanteras, patas y mandíbulas musculares.",
                            Diet = "Carnivore",
                            EstimatedPopulationSize = 30000,
                            Locations = "3",
                            ScientificName = "Felis Concolor"
                        },
                        new
                        {
                            Id = 18,
                            AverageHeightMax = 74,
                            AverageHeightMin = 48,
                            AverageLifespanMax = 25,
                            AverageLifespanMin = 15,
                            AverageSpeedMax = 25,
                            AverageSpeedMin = 15,
                            AverageWeightMax = 115,
                            AverageWeightMin = 90,
                            CommonName = "Asiatic Black Bear",
                            Description = "El oso negro asiático, también conocido como oso negro del Himalaya o oso luna, es un oso omnívoro que habita en los bosques tropicales caducifolios del sur y centro de Asia. Se caracteriza por su distintiva marca en forma de 'V' en el pecho.",
                            Diet = "Omnivore",
                            EstimatedPopulationSize = 50000,
                            Locations = "1",
                            ScientificName = "Ursus tibetanus"
                        },
                        new
                        {
                            Id = 19,
                            AverageHeightMax = 109,
                            AverageHeightMin = 59,
                            AverageLifespanMax = 30,
                            AverageLifespanMin = 20,
                            AverageSpeedMax = 35,
                            AverageSpeedMin = 25,
                            AverageWeightMax = 390,
                            AverageWeightMin = 136,
                            CommonName = "Brown Bear",
                            Description = "El oso pardo o oso grizzly es una poderosa especie de oso omnívoro que habita en las regiones forestales y montañosas del hemisferio norte. Se caracteriza por su fuerza, garras afiladas y hábito hibernante.",
                            Diet = "Omnivore",
                            EstimatedPopulationSize = 200000,
                            Locations = "1;6;3",
                            ScientificName = "Ursus arctos"
                        },
                        new
                        {
                            Id = 20,
                            AverageHeightMax = 70,
                            AverageHeightMin = 59,
                            AverageLifespanMax = 35,
                            AverageLifespanMin = 20,
                            AverageSpeedMax = 20,
                            AverageSpeedMin = 10,
                            AverageWeightMax = 250,
                            AverageWeightMin = 110,
                            CommonName = "Giant Panda Bear",
                            Description = "El oso panda gigante es una especie única de oso herbívoro que habita en las montañas del centro de China. Se caracteriza por su distintivo pelaje blanco y negro, y su habilidad para consumir bambú.",
                            Diet = "Omnivore",
                            EstimatedPopulationSize = 2000,
                            Locations = "1",
                            ScientificName = "Ailuropoda melanoleuca"
                        },
                        new
                        {
                            Id = 21,
                            AverageHeightMax = 118,
                            AverageHeightMin = 84,
                            AverageLifespanMax = 25,
                            AverageLifespanMin = 15,
                            AverageSpeedMax = 35,
                            AverageSpeedMin = 25,
                            AverageWeightMax = 318,
                            AverageWeightMin = 181,
                            CommonName = "Grizzly Bear",
                            Description = "El oso grizzly o oso pardo es una subespecie del oso pardo conocido por su gran tamaño, fuerza y garras enormes. Habita en las regiones forestales y montañosas del oeste de América del Norte.",
                            Diet = "Omnivore",
                            EstimatedPopulationSize = 50000,
                            Locations = "3",
                            ScientificName = "Ursus Arctos Horriblis"
                        },
                        new
                        {
                            Id = 22,
                            AverageHeightMax = 70,
                            AverageHeightMin = 51,
                            AverageLifespanMax = 30,
                            AverageLifespanMin = 15,
                            AverageSpeedMax = 30,
                            AverageSpeedMin = 20,
                            AverageWeightMax = 270,
                            AverageWeightMin = 100,
                            CommonName = "North American Black Bear",
                            Description = "El oso negro americano es una especie de oso omnívoro que habita en las regiones boscosas y arboladas de América del Norte. Se caracteriza por su grueso pelaje y hocico puntiagudo.",
                            Diet = "Omnivore",
                            EstimatedPopulationSize = 800000,
                            Locations = "3",
                            ScientificName = "Ursus americanus"
                        },
                        new
                        {
                            Id = 23,
                            AverageHeightMax = 98,
                            AverageHeightMin = 78,
                            AverageLifespanMax = 30,
                            AverageLifespanMin = 20,
                            AverageSpeedMax = 25,
                            AverageSpeedMin = 15,
                            AverageWeightMax = 600,
                            AverageWeightMin = 150,
                            CommonName = "Polar Bear",
                            Description = "El oso polar es una especie de oso carnívoro que habita en las regiones costeras y campos de hielo del Ártico. Se caracteriza por su pelaje blanco y piel negra, adaptado al entorno ártico.",
                            Diet = "Carnivore",
                            EstimatedPopulationSize = 22500,
                            Locations = "1;6;3;7",
                            ScientificName = "Ursus maritimus"
                        },
                        new
                        {
                            Id = 24,
                            AverageHeightMax = 78,
                            AverageHeightMin = 59,
                            AverageLifespanMax = 30,
                            AverageLifespanMin = 20,
                            AverageSpeedMax = 30,
                            AverageSpeedMin = 20,
                            AverageWeightMax = 200,
                            AverageWeightMin = 130,
                            CommonName = "Spectacled Bear",
                            Description = "El oso de anteojos o oso andino es una especie de oso omnívoro que habita en las regiones costeras y desérticas de los Andes en Sudamérica. Se caracteriza por sus distintivas marcas claras alrededor de los ojos.",
                            Diet = "Omnivore",
                            EstimatedPopulationSize = 20000,
                            Locations = "4",
                            ScientificName = "Tremarctos Ornatus"
                        },
                        new
                        {
                            Id = 25,
                            AverageHeightMax = 59,
                            AverageHeightMin = 47,
                            AverageLifespanMax = 30,
                            AverageLifespanMin = 15,
                            AverageSpeedMax = 30,
                            AverageSpeedMin = 20,
                            AverageWeightMax = 60,
                            AverageWeightMin = 30,
                            CommonName = "Sun Bear",
                            Description = "El oso malayo o oso de las mieles es la especie más pequeña de oso existente. Habita en los bosques tropicales del sureste asiático y se caracteriza por su distintiva marca en forma de 'U' en el pecho.",
                            Diet = "Omnivore",
                            EstimatedPopulationSize = 10000,
                            Locations = "1",
                            ScientificName = "Helarctos malayanus"
                        },
                        new
                        {
                            Id = 26,
                            AverageHeightMax = 31,
                            AverageHeightMin = 20,
                            AverageLifespanMax = 15,
                            AverageLifespanMin = 12,
                            AverageSpeedMax = 34,
                            AverageSpeedMin = 24,
                            AverageWeightMax = 33,
                            AverageWeightMin = 9,
                            CommonName = "Bobcat",
                            Description = "El lince rojo o gato bobcat es un felino de tamaño mediano que habita en América del Norte y algunas regiones de América Central. Se caracteriza por sus distintivas orejas con penachos y su cola corta.",
                            Diet = "Carnivore",
                            EstimatedPopulationSize = 1000000,
                            Locations = "3",
                            ScientificName = "Lynx rufus"
                        },
                        new
                        {
                            Id = 27,
                            AverageHeightMax = 71,
                            AverageHeightMin = 60,
                            AverageLifespanMax = 35,
                            AverageLifespanMin = 20,
                            AverageSpeedMax = 20,
                            AverageSpeedMin = 10,
                            AverageWeightMax = 551,
                            AverageWeightMin = 242,
                            CommonName = "Giant Panda Bear",
                            Description = "El oso panda gigante es una especie única de oso herbívoro que habita en las montañas del centro de China. Se caracteriza por su distintivo pelaje blanco y negro, y su habilidad para consumir bambú.",
                            Diet = "Omnivore",
                            EstimatedPopulationSize = 2000,
                            Locations = "1",
                            ScientificName = "Ailuropoda melanoleuca"
                        },
                        new
                        {
                            Id = 28,
                            AverageHeightMax = 47,
                            AverageHeightMin = 24,
                            AverageLifespanMax = 12,
                            AverageLifespanMin = 8,
                            AverageSpeedMax = 24,
                            AverageSpeedMin = 14,
                            AverageWeightMax = 14,
                            AverageWeightMin = 7,
                            CommonName = "Red Panda",
                            Description = "La panda roja o panda menor es una especie de mamífero omnívoro que habita en las montañas del Himalaya. Se caracteriza por su grueso pelaje rojizo y cara rayada.",
                            Diet = "Omnivore",
                            EstimatedPopulationSize = 3000,
                            Locations = "1",
                            ScientificName = "Ailurus fulgens"
                        },
                        new
                        {
                            Id = 29,
                            AverageHeightMax = 0,
                            AverageHeightMin = 0,
                            AverageLifespanMax = 50,
                            AverageLifespanMin = 45,
                            AverageSpeedMax = 40,
                            AverageSpeedMin = 40,
                            AverageWeightMax = 3100,
                            AverageWeightMin = 1800,
                            CommonName = "Black Rhinoceros",
                            Description = "You can replace this with a description retrieved from the web about Black Rhinoceros.",
                            Diet = "Herbivore",
                            EstimatedPopulationSize = 0,
                            Locations = "2",
                            ScientificName = "Diceros Bicornis"
                        },
                        new
                        {
                            Id = 30,
                            AverageHeightMax = 0,
                            AverageHeightMin = 0,
                            AverageLifespanMax = 50,
                            AverageLifespanMin = 45,
                            AverageSpeedMax = 30,
                            AverageSpeedMin = 30,
                            AverageWeightMax = 6600,
                            AverageWeightMin = 4900,
                            CommonName = "Indian Rhinoceros",
                            Description = "You can replace this with a description retrieved from the web about Indian Rhinoceros.",
                            Diet = "Herbivore",
                            EstimatedPopulationSize = 0,
                            Locations = "1",
                            ScientificName = "Rhinoceros Unicornis"
                        },
                        new
                        {
                            Id = 31,
                            AverageHeightMax = 0,
                            AverageHeightMin = 0,
                            AverageLifespanMax = 50,
                            AverageLifespanMin = 45,
                            AverageSpeedMax = 30,
                            AverageSpeedMin = 30,
                            AverageWeightMax = 7920,
                            AverageWeightMin = 3168,
                            CommonName = "White Rhinoceros",
                            Description = "You can replace this with a description retrieved from the web about White Rhinoceros.",
                            Diet = "Herbivore",
                            EstimatedPopulationSize = 0,
                            Locations = "2",
                            ScientificName = "Ceratotherium simum"
                        },
                        new
                        {
                            Id = 32,
                            AverageHeightMax = 350,
                            AverageHeightMin = 300,
                            AverageLifespanMax = 70,
                            AverageLifespanMin = 60,
                            AverageSpeedMax = 25,
                            AverageSpeedMin = 25,
                            AverageWeightMax = 5400,
                            AverageWeightMin = 3600,
                            CommonName = "African Bush Elephant",
                            Description = "The African Bush Elephant is the largest living land animal.  They have large,扇形 (shàn xíng - fan-shaped) ears to help radiate heat and wrinkled gray skin.  Their tusks are long and curved outwards.  These gentle giants are social creatures living in herds led by females.",
                            Diet = "Herbivore",
                            EstimatedPopulationSize = 300000,
                            Locations = "2",
                            ScientificName = "Loxodonta africana africana"
                        },
                        new
                        {
                            Id = 33,
                            AverageHeightMax = 300,
                            AverageHeightMin = 200,
                            AverageLifespanMax = 70,
                            AverageLifespanMin = 60,
                            AverageSpeedMax = 24,
                            AverageSpeedMin = 24,
                            AverageWeightMax = 3000,
                            AverageWeightMin = 900,
                            CommonName = "African Forest Elephant",
                            Description = "The African Forest Elephant is smaller and darker than its savanna relative.  They have characteristically rounded ears and a hairy trunk.  An African forest elephant's tusks are straighter and point downward, rather outwards like savanna elephants.  They play a vital role in seed dispersal by consuming a diet rich in fruits.",
                            Diet = "Herbivore",
                            EstimatedPopulationSize = 200000,
                            Locations = "2",
                            ScientificName = "Loxodonta cyclotis"
                        },
                        new
                        {
                            Id = 34,
                            AverageHeightMax = 20,
                            AverageHeightMin = 17,
                            AverageLifespanMax = 10,
                            AverageLifespanMin = 6,
                            AverageSpeedMax = 32,
                            AverageSpeedMin = 24,
                            AverageWeightMax = 30,
                            AverageWeightMin = 20,
                            CommonName = "Pájaro Azul Oriental",
                            Description = "Un ave cantora pequeña y colorida que habita en bosques abiertos y áreas suburbanas de América del Norte. Se caracteriza por su plumaje azul brillante en los machos y azul más pálido en las hembras.",
                            Diet = "Omnívora (fruta favorita)",
                            EstimatedPopulationSize = 900000,
                            Locations = "3",
                            ScientificName = "Sialia sialis"
                        },
                        new
                        {
                            Id = 35,
                            AverageHeightMax = 10,
                            AverageHeightMin = 5,
                            AverageLifespanMax = 8,
                            AverageLifespanMin = 3,
                            AverageSpeedMax = 90,
                            AverageSpeedMin = 50,
                            AverageWeightMax = 6,
                            AverageWeightMin = 2,
                            CommonName = "Colibrí",
                            Description = "Las aves más pequeñas del mundo, conocidas por su vuelo acrobático y su capacidad para alimentarse de néctar. Se encuentran en diversos hábitats de América Central, Norte y Sur.",
                            Diet = "Nectarívora",
                            EstimatedPopulationSize = 340,
                            Locations = "3;4",
                            ScientificName = "Familia Trochilidae"
                        },
                        new
                        {
                            Id = 36,
                            AverageHeightMax = 10,
                            AverageHeightMin = 5,
                            AverageLifespanMax = 8,
                            AverageLifespanMin = 3,
                            AverageSpeedMax = 90,
                            AverageSpeedMin = 50,
                            AverageWeightMax = 6,
                            AverageWeightMin = 2,
                            CommonName = "Colibrí Rubí Garganta",
                            Description = "Un colibrí de tamaño mediano con garganta roja brillante. Habita en bosques, jardines y campos de América del Norte. Construye nidos con telarañas y líquenes.",
                            Diet = "Nectarívora",
                            EstimatedPopulationSize = 36000000,
                            Locations = "3",
                            ScientificName = "Archilochus colubris"
                        },
                        new
                        {
                            Id = 37,
                            AverageHeightMax = 129,
                            AverageHeightMin = 48,
                            AverageLifespanMax = 35,
                            AverageLifespanMin = 15,
                            AverageSpeedMax = 35,
                            AverageSpeedMin = 20,
                            AverageWeightMax = 450,
                            AverageWeightMin = 27,
                            CommonName = "Bear",
                            Description = "Los osos son mamíferos omnívoros de la familia Ursidae, conocidos por su gran tamaño, fuerza y garras afiladas. Habitan en regiones forestales y montañosas de diferentes partes del mundo.",
                            Diet = "Omnivore",
                            EstimatedPopulationSize = 1000000,
                            Locations = "1;6;3;4",
                            ScientificName = "Ursidae"
                        });
                });

            modelBuilder.Entity("WildAnimalsAPI.Models.Continent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.Property<long>("SurfaceKm2")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Continents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Asia",
                            Population = 4693000000L,
                            SurfaceKm2 = 44614000L
                        },
                        new
                        {
                            Id = 2,
                            Name = "Africa",
                            Population = 1386000000L,
                            SurfaceKm2 = 30370000L
                        },
                        new
                        {
                            Id = 3,
                            Name = "America del Norte",
                            Population = 593000000L,
                            SurfaceKm2 = 24709000L
                        },
                        new
                        {
                            Id = 4,
                            Name = "America del Sur",
                            Population = 434000000L,
                            SurfaceKm2 = 17843000L
                        },
                        new
                        {
                            Id = 5,
                            Name = "Antártida",
                            Population = 0L,
                            SurfaceKm2 = 14200000L
                        },
                        new
                        {
                            Id = 6,
                            Name = "Europa",
                            Population = 741000000L,
                            SurfaceKm2 = 10180000L
                        },
                        new
                        {
                            Id = 7,
                            Name = "Oceanía",
                            Population = 44000000L,
                            SurfaceKm2 = 8920000L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
